### ISSUE TITLE
运行报错了，请看下

### ISSUE THREAD

**Issue by yinyangwu** [zhanlan123/YXlogDecode#2]
![WX20230314-161624@2x](https://user-images.githubusercontent.com/7466810/224938098-8633b992-2d5c-4588-8ef0-2b5ee3ebf804.png)

解密开始运行

直接增加需要解密的日志文件：C:\Users\admin\Desktop\logs_20230314.xlog

开始解密：C:\Users\admin\Desktop\logs_20230314.xlog

开始解密：logs_20230314.xlog

异常信息：java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.done(DecodeFrame.java:1002)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:614)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.DecodeBuffer(XLogFileDecode.java:214)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.ParseFile(XLogFileDecode.java:257)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:995)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:976)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

解密完成

**Comment by yinyangwu** [comment]
解密开始运行

直接增加需要解密的日志文件：C:\Users\admin\Desktop\logs_20230314.xlog

开始解密：C:\Users\admin\Desktop\logs_20230314.xlog

开始解密：logs_20230314.xlog

异常信息：java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
	at org.bouncycastle.crypto.params.ECDomainParameters.validatePrivateScalar(ECDomainParameters.java:146)
	at org.bouncycastle.crypto.params.ECPrivateKeyParameters.<init>(ECPrivateKeyParameters.java:16)
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(ECUtil.java:245)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi.doInitFromKey(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseAgreementSpi.engineInit(Unknown Source)
	at java.base/javax.crypto.KeyAgreement.init(KeyAgreement.java:475)
	at java.base/javax.crypto.KeyAgreement.init(KeyAgreement.java:449)
	at top.yinlingfeng.xlog.decode.core.ECDHUtils.getECDHKey(ECDHUtils.java:40)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.DecodeBuffer(XLogFileDecode.java:187)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.ParseFile(XLogFileDecode.java:257)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:995)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:976)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


解密完成

<img width="711" alt="企业微信截图_140e8870-a0f7-49b0-8f1e-1a1580f15aba" src="https://user-images.githubusercontent.com/7466810/224935325-53b95ae7-82b8-40b5-9cde-a1f2c71c60a3.png">

**Comment by zhanlan123** [comment]
能否说下，用的xlog哪个版本。

**Comment by zhanlan123** [comment]
你这是密钥错误了。如果你的密钥是手动填入的，请勾选：输入密钥，如果是已经保存的密钥才勾选：选择密钥。我测试了1.0.5-1.2.6都是可以解密的。
