### ISSUE TITLE
1.5版本，无加密解码失败

### ISSUE THREAD

**Issue by shuimuqinghua** [zhanlan123/YXlogDecode#4]
步骤：
1. 使用Xlog里面的代码运行，获取日志。xlog里面的pubkey=“”；
2. 使用1.5版本exe文件解密，将test密钥删掉，使用输入密钥里面的默认是，报错如下。
3. 删除test密钥，输入密钥框里面内容清空，提示密钥不能为空。

请帮忙看看是什么错，万分感谢！

解密开始运行

直接增加需要解密的日志文件：C:\Users\tssh\Desktop\LOGSAMPLE_20230420.xlog

开始解密：C:\Users\tssh\Desktop\LOGSAMPLE_20230420.xlog

开始解密：LOGSAMPLE_20230420.xlog

异常信息：java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
 at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
 at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
 at java.desktop/javax.swing.SwingWorker.get(Unknown Source)
 at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.done(DecodeFrame.java:1024)
 at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
 at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
 at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
 at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
 at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
 at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Unknown Source)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused

**Comment by zhanlan123** [comment]
稍等我看看

**Comment by zhanlan123** [comment]
有个逻辑没有说明，如果是只压缩，无加密的文件，可以随便选择一个密钥。因为内部判断是不是加密是读取文件判断的。
所以，你的无加密文件，可以随便选择一个密钥。你试试看看可以正常解压缩吗？如果不行，就需要发一个测试的压缩文件给我。

**Comment by shuimuqinghua** [comment]
> 有个逻辑没有说明，如果是只压缩，无加密的文件，可以随便选择一个密钥。因为是根据文件内容判断是不是加密是的。 所以，你的无加密文件，可以随便选择一个密钥。你试试看看可以正常解压缩吗？如果不行，就需要发一个测试的压缩文件给我。

你好，今天试了下，直接选Test密钥解密，还是会报错。错误如下：
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null

**Comment by zhanlan123** [comment]
我这边生成一个测试文件测试，只zip压缩，是可以解密的。我怀疑是你的这个是加密的。你输入你自己的密钥试试可不可以解密。

**Comment by zhanlan123** [comment]
我这边增加了一个只zip压缩的文件，用于单元测试，你可以试试。

**Comment by zhanlan123** [comment]
如果，还是不行，就需要看看你的代码，或者给我密钥。或者你用测试的公钥加密试试：94e62d97637f357fbd20f0c1f667a67c2f675e158e46015dd0cc54cb3995d0a5d468f7e98b20aec266effb61ec0a2321fb1f8c61af72bf76567921a0d8305005
