### ISSUE TITLE
win10用桌面带jre工具解密报错

### ISSUE THREAD

**Issue by zhuzhutai** [zhanlan123/YXlogDecode#7]
开始解密：C:\Users\97859\Desktop\X_20230704.xlog

开始解密：X_20230704.xlog

异常信息：java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
	at org.bouncycastle.crypto.params.ECDomainParameters.validatePrivateScalar(ECDomainParameters.java:146)
	at org.bouncycastle.crypto.params.ECPrivateKeyParameters.<init>(ECPrivateKeyParameters.java:16)
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(ECUtil.java:245)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi.doInitFromKey(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseAgreementSpi.engineInit(Unknown Source)
	at java.base/javax.crypto.KeyAgreement.init(Unknown Source)
	at java.base/javax.crypto.KeyAgreement.init(Unknown Source)
	at top.yinlingfeng.xlog.decode.core.ECDHUtils.getECDHKey(ECDHUtils.java:40)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.DecodeBuffer(XLogFileDecode.java:187)
	at top.yinlingfeng.xlog.decode.core.XLogFileDecode.ParseFile(XLogFileDecode.java:257)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:1017)
	at top.yinlingfeng.xlog.decode.ui.DecodeFrame$DecodeLogTask.doInBackground(DecodeFrame.java:998)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by zhanlan123** [comment]
看堆栈是密钥错误，看看你选择的密钥是否正确，能否提供一个日志文件用于测试一下。

**Comment by zhanlan123** [comment]
如果可以用这个测试公钥替换你现在的公钥：94e62d97637f357fbd20f0c1f667a67c2f675e158e46015dd0cc54cb3995d0a5d468f7e98b20aec266effb61ec0a2321fb1f8c61af72bf76567921a0d8305005
然后发一个xlog文件给我测试一下。

**Comment by zhanlan123** [comment]
1.6 打包错误。打包的jdk不是openJdk

**Comment by zhuzhutai** [comment]
感谢回复，把本地的jre环境copy到程序目录就可以了！
